title:              Go the Distance
email:              andrea.hill@gmail.com
description:        A Running and Training Blog by Andrea Hill
author:             Andrea Hill
baseurl:            "/gothedistance"
url:                "https://afhill.github.io"

# Social Profiles
twitter_username:   afhill
#github_username:    BlackrockDigital

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code



# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
